name: Build and Deploy llama.cpp Server to GHCR (tag)
on:
  push:
    tags: [ '*' ]
env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  IMAGE_PREFIX: llama.cpp-server
jobs:
  build-and-push-image:
    strategy:
      matrix:
        include:
          - model_quantization: "Phi-3.5-mini-instruct-IQ2_M.gguf"
            model_quantization_lowercase: "phi-3.5-mini-instruct-iq2_m.gguf"
          - model_quantization: "Phi-3.5-mini-instruct-Q4_K_L.gguf"
            model_quantization_lowercase: "phi-3.5-mini-instruct-q4_k_l.gguf"
          - model_quantization: "Phi-3.5-mini-instruct-Q8_0.gguf"
            model_quantization_lowercase: "phi-3.5-mini-instruct-q8_0.gguf"
          # Add more combinations as needed
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get the tag name
      id: get_tag
      run: |
        # Extract the tag name without the 'refs/tags/' prefix
        echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      env:
        IMAGE_NAME: ${{ env.IMAGE_PREFIX }}-${{ matrix.model_quantization_lowercase }}
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:${{ steps.get_tag.outputs.TAG_NAME }}
        build-args: |
          MODEL_QUANTIZATION=${{ matrix.model_quantization }}
